reqtracker/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',views.login_request,name='login'),
    path('login/',views.login_request,name='login'),
    path('logout/',views.logout_request,name='logout'),
    path('dashboard/',views.view_home,name='dash'),
    path('dashboard-user/',views.view_dash_user,name='dashboard-user'),
    path('dashboard-admin/',views.view_dash_admin,name='dashboard-admin'),
    path('dashboard-super/',views.view_dash_super,name='dashboard-super'),
    path('initial/<str:r>/estimation_report/',views.view_estimation,name='estimation_report'),
    path('final/<str:r>/estimation_report/',views.view_estimation,name='estimation_report'),
    path('<str:r>/completion_report/',views.view_completion_form,name='completion_report'),
    path('view_request/<str:pk_r>/',views.view_request,name='view_request'),
    path('view_req_admin/<str:pk_r>/',views.view_request_admin,name='view_admin'),
    path('create_request/',views.create_request,name='create_request'),
    path('update_request/admin/<str:pk>/',views.update_req_admin,name='update_request_admin'),
    path('update_request/user/<str:pk>/',views.update_req_user,name='update_request_user'),
    path('delete_request/<str:pk>/',views.del_req,name='del_req'),
    path('update_status/<str:pk>/',views.update_status,name='update_status'),
    path('update_estimate/<str:pk>/',views.update_estimate,name='update_estimate'),
    path('delete_estimate/<str:pk>/',views.delete_estimate,name='delete_estimate'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('reqtracker.urls')),

]

reqtracker/models.py
from django.db import models
from random import sample
import datetime
from django.contrib.auth.models import User
from django_currentuser.db.models import CurrentUserField

# Create your models here.
MAIN_TYPE = (
    ('Corrective Maintenance','Corrective Maintenance'),
    ('Scheduled Maintenance','Scheduled Maintenance')
)

TYPE_MAIN = (
    ('Civil','CIVIL'),
    ('MEP','MEP')
)

NATURE_CIVIL = (
    ('Painting','Painting'),
    ('Carpentry','Carpentry'),
    ('Masonry','Masonry')
)

NATURE_MEP = (
    ('Mechanical - Pump, motors, HVAC','Mechanical - Pump, motors, HVAC'),
    ('Electrical - lighting, switch','Electrical - lighting, switch'),
    ('Plumbing','Plumbing')
)

TYPE = (
    ('Normal','Normal'),
    ('Urgent','Urgent'),
    ('Emergency','Emergency'),
    ('Other','Other')
)
STATUS = (
    ('Pending','Pending'),
    ('Completed','Completed'),
    ('In Progress','In Progress')
)
ITEMS = (
    ('Paint','Paint'),
    ('Manpower','Manpower'),
    ('Cement','Cement'),
    ('Steel','Steel'),
    ('Concrete','Concrete'),
    ('Glass','Glass'),
    ('Brick','Brick'),
)

class Item(models.Model):
    item_code = models.IntegerField()
    item = models.CharField(choices=ITEMS,max_length=200)
    price = models.IntegerField()
    
    def __str__(self):
        return self.item
    


class MainRequest(models.Model):
    
    def create_request_no():
        z = 'RM'+''.join(sample("0123456789", 4))
        return z
    
    user = CurrentUserField()
    Request_Number = models.CharField(default=create_request_no(), unique=True, max_length=100)
    Maintenance = models.CharField(default='Corrective Maintenance', max_length=100)
    Maintenance_Type = models.CharField(choices=TYPE_MAIN, max_length=200)
    Nature_Civil = models.CharField(choices=NATURE_CIVIL, max_length=200,  null=True, blank=True)
    Nature_MEP = models.CharField(choices=NATURE_MEP, max_length=200, null=True, blank=True)
    Type_Nature = models.CharField(choices=TYPE, max_length=200)
    Zone = models.CharField(max_length=200)
    Flat = models.CharField(max_length=200)
    Building = models.CharField(max_length=200)
    Floor = models.CharField(max_length=200)
    Complaint_Details = models.TextField(max_length=200)
    date_created = models.DateTimeField(default=datetime.datetime.today(),editable=False)
    status = models.CharField(choices=STATUS,default='Pending', max_length=20) 
    expected_date_n = models.DateTimeField(default=datetime.datetime.today() + datetime.timedelta(days=10),editable=False)
    expected_date_u = models.DateTimeField(default=datetime.datetime.today() + datetime.timedelta(days=1),editable=False)
    expected_date_i = models.DateTimeField(default=datetime.datetime.today() + datetime.timedelta(days=3),editable=False)
    expected_date_o = models.DateTimeField(default=datetime.datetime.today() + datetime.timedelta(days=10),editable=False)
    # image_1 = models.ImageField(blank=True, null=True)
    # image_2 = models.ImageField(blank=True, null=True)
    # after_image_1 = models.ImageField(blank=True, null=True)
    # after_image_2 = models.ImageField(blank=True, null=True)

    def __str__(self):
        return self.Request_Number

class Completion(models.Model):
    mr = models.ForeignKey(MainRequest, to_field='Request_Number', on_delete=models.CASCADE,blank=True,null=True)
    user = CurrentUserField()
    tech_name = models.CharField(max_length=30)
    date_created = models.DateTimeField(default=datetime.datetime.today(),editable=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    unit = models.CharField(max_length=15)
    work_details = models.TextField(max_length=200)
    
    def __str__(self):
        return str(self.mr)
    
    @property
    def total_price(self):
        tp = self.quantity * self.item.price
        return tp
    



    

reqtracker/forms.py
#from django.forms import ModelForm
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

#Form for user's 
class MainRequestForm(forms.ModelForm):
    class Meta:
        model = MainRequest
        fields = ['Request_Number','Maintenance','Maintenance_Type','Nature_Civil','Nature_MEP','Type_Nature','Zone','Flat','Building','Floor','Complaint_Details']

#Form for clients	
class MainRequestFormAdmin(forms.ModelForm):
    class Meta:
        model = MainRequest
        fields = ['Request_Number','Maintenance','Maintenance_Type','Nature_Civil','Nature_MEP','Type_Nature','Zone','Flat','Building','Floor','Complaint_Details','status']

#Form for registration
class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("first_name","last_name","username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user
        
class StatusUpdateForm(forms.ModelForm):
    class Meta:
        model = MainRequest
        fields = ('Request_Number','status')
        
class CompletionForm(forms.ModelForm):
    class Meta:
        model = Completion
        fields = ('mr','tech_name','item','quantity','unit','work_details')

reqtracker/views.py
from django.shortcuts import render , redirect
from .models import *
from .forms import *
import datetime
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django_currentuser.middleware import (
    get_current_user, get_current_authenticated_user)

# Create your views here.
@login_required
def view_home(request):
    return render(request, 'reqtracker/dashboard.html')

#View user dashboard
@login_required
def view_dash_user(request):

    requests = MainRequest.objects.filter(user=request.user)
    # req_p = MainRequest.objects.filter(status="Pending",user=request.user)
    # req_c = MainRequest.objects.filter(status="Completed",user=request.user))
    # req_i = MainRequest.objects.filter(status="In Progress",user=request.user))
    
    labels = ['Pending','In Progress','Completed']
    labels1 = ['Civil','MEP']
    queryset = MainRequest.objects.filter(status='Pending',user=request.user)
    queryset1 = MainRequest.objects.filter(status='In Progress',user=request.user)
    queryset2 = MainRequest.objects.filter(status='Completed',user=request.user)
    queryset3 = MainRequest.objects.filter(Maintenance_Type='Civil',user=request.user).count()
    queryset4 = MainRequest.objects.filter(Maintenance_Type='MEP',user=request.user).count()
    data = [queryset.count(),queryset1.count(),queryset2.count()]
    data1 = [queryset3,queryset4]
    return render(request, 'reqtracker/dashboard-user.html',{
        'requests':requests,
        'labels':labels,
        'data':data,
        'labels1':labels1,
        'data1':data1,
        'queryset':queryset,
        'queryset1':queryset1,
        'queryset2':queryset2
        })

#View admin dashboard
@login_required
def view_dash_admin(request):
    labels = ['Pending','In Progress','Completed']
    labels1 = ['Civil','MEP']
    labels2 = ['Painting','Carpentry','Masonry']
    labels3 = ['Mechanical','Electrical','Plumbing']
    queryset = MainRequest.objects.filter(status='Pending').count()
    queryset1 = MainRequest.objects.filter(status='In Progress').count()
    queryset2 = MainRequest.objects.filter(status='Completed').count()
    queryset3 = MainRequest.objects.filter(Maintenance_Type='Civil').count()
    queryset4 = MainRequest.objects.filter(Maintenance_Type='MEP').count()
    queryset5 = MainRequest.objects.filter(Nature_Civil='Painting').count()
    queryset6 = MainRequest.objects.filter(Nature_Civil='Carpentry').count()
    queryset7 = MainRequest.objects.filter(Nature_Civil='Masonry').count()
    queryset8 = MainRequest.objects.filter(Nature_MEP='Mechanical - Pump, motors, HVAC').count()
    queryset9 = MainRequest.objects.filter(Nature_MEP='Electrical - lighting, switch').count()
    queryset10 = MainRequest.objects.filter(Nature_MEP='Plumbing').count()
    data = [queryset,queryset1,queryset2]
    data1 = [queryset3,queryset4]
    data2 = [queryset5,queryset6,queryset7]
    data3 = [queryset8,queryset9,queryset10]
    
    requests = MainRequest.objects.all()
    todays_req = MainRequest.objects.filter(date_created=datetime.date.today())
    req_pending = MainRequest.objects.filter(status="Pending")
    req_completed = MainRequest.objects.filter(status="Completed")
    req_in = MainRequest.objects.filter(status="In Progress")
    context = {
        'requests':requests,
        'tr':todays_req,
        'labels':labels,
        'data':data,
        'labels1':labels1,
        'data1':data1,
        'labels2':labels2,
        'data2':data2,
        'labels3':labels3,
        'data3':data3,
        'req_pending':req_pending,
        'req_completed':req_completed,
        'req_in':req_in
    }
    return render(request, 'reqtracker/dashboard-admin.html',context)

#View supervisor dashboard
@login_required
def view_dash_super(request):
    labels = ['Pending','In Progress','Completed']
    if request.user.username == "SPRC1":
        req = MainRequest.objects.filter(Maintenance_Type='Civil',Zone__in=['1','2','3','4','5'])
        queryset = MainRequest.objects.filter(Maintenance_Type='Civil',Zone__in=['1','2','3','4','5'],status='Pending')
        queryset1 = MainRequest.objects.filter(Maintenance_Type='Civil',Zone__in=['1','2','3','4','5'],status='In Progress')
        queryset2 = MainRequest.objects.filter(Maintenance_Type='Civil',Zone__in=['1','2','3','4','5'],status='Completed')
        z1 = MainRequest.objects.filter(Maintenance_Type='Civil', Zone='1').count()
        z2 = MainRequest.objects.filter(Maintenance_Type='Civil', Zone='2').count()
        z3 = MainRequest.objects.filter(Maintenance_Type='Civil', Zone='3').count()
        z4 = MainRequest.objects.filter(Maintenance_Type='Civil', Zone='4').count()
        z5 = MainRequest.objects.filter(Maintenance_Type='Civil', Zone='5').count()
        data = [queryset.count(),queryset1.count(),queryset2.count()]
        data2 = [z1,z2,z3,z4,z5]
        t = ['Civil']
        labels2 = ["Zone 01", "Zone 02", "Zone 03",'Zone 04','Zone 05']
        return render(request,'reqtracker/dashboard-super.html',{
            'req':req,
            'labels':labels,
            'data':data,
            'data2':data2,
            'labels2':labels2,
            't':t,
            'queryset':queryset,
            'queryset1':queryset1,
            'queryset2':queryset2
            })
    elif request.user.username == "SPRC2":
        req = MainRequest.objects.filter(Maintenance_Type='Civil',Zone__in=['6','7','8','9','10'])
        queryset = MainRequest.objects.filter(Maintenance_Type='Civil',Zone__in=['6','7','8','9','10'],status='Pending')
        queryset1 = MainRequest.objects.filter(Maintenance_Type='Civil',Zone__in=['6','7','8','9','10'],status='In Progress')
        queryset2 = MainRequest.objects.filter(Maintenance_Type='Civil',Zone__in=['6','7','8','9','10'],status='Completed')
        z6 = MainRequest.objects.filter(Maintenance_Type='Civil', Zone='6').count()
        z7 = MainRequest.objects.filter(Maintenance_Type='Civil', Zone='7').count()
        z8 = MainRequest.objects.filter(Maintenance_Type='Civil', Zone='8').count()
        z9 = MainRequest.objects.filter(Maintenance_Type='Civil', Zone='9').count()
        z10 = MainRequest.objects.filter(Maintenance_Type='Civil', Zone='10').count()
        data = [queryset.count(),queryset1.count(),queryset2.count()]
        data2 = [z6,z7,z8,z9,z10]
        t = ['Civil']
        labels2 = ["Zone 06", "Zone 07", "Zone 08",'Zone 09','Zone 10']
        return render(request,'reqtracker/dashboard-super.html',{
            'req':req,
            'labels':labels,
            'data':data,
            'data2':data2,
            'labels2':labels2,
            't':t,
            'queryset':queryset,
            'queryset1':queryset1,
            'queryset2':queryset2
            })
    elif request.user.username == "SPRMEP1":
        req = MainRequest.objects.filter(Maintenance_Type='MEP',Zone__in=['1','2','3','4','5'])
        queryset = MainRequest.objects.filter(Maintenance_Type='MEP',Zone__in=['1','2','3','4','5'],status='Pending')
        queryset1 = MainRequest.objects.filter(Maintenance_Type='MEP',Zone__in=['1','2','3','4','5'],status='In Progress')
        queryset2 = MainRequest.objects.filter(Maintenance_Type='MEP',Zone__in=['1','2','3','4','5'],status='Completed')
        data = [queryset.count(),queryset1.count(),queryset2.count()]
        z1 = MainRequest.objects.filter(Maintenance_Type='MEP', Zone='1').count()
        z2 = MainRequest.objects.filter(Maintenance_Type='MEP', Zone='2').count()
        z3 = MainRequest.objects.filter(Maintenance_Type='MEP', Zone='3').count()
        z4 = MainRequest.objects.filter(Maintenance_Type='MEP', Zone='4').count()
        z5 = MainRequest.objects.filter(Maintenance_Type='MEP', Zone='5').count()
        data2 = [z1,z2,z3,z4,z5]
        t=['MEP']
        labels2 = ["Zone 01", "Zone 02", "Zone 03",'Zone 04','Zone 05']
        return render(request,'reqtracker/dashboard-super.html',{
            'req':req,
            'labels':labels,
            'data':data,
            'data2':data2,
            'labels2':labels2,
            't':t,
            'queryset':queryset,
            'queryset1':queryset1,
            'queryset2':queryset2
            })
    elif request.user.username == "SPRMEP2":
        req = MainRequest.objects.filter(Maintenance_Type='MEP',Zone__in=['6','7','8','9','10'])
        queryset = MainRequest.objects.filter(Maintenance_Type='MEP',Zone__in=['6','7','8','9','10'],status='Pending')
        queryset1 = MainRequest.objects.filter(Maintenance_Type='MEP',Zone__in=['6','7','8','9','10'],status='In Progress')
        queryset2 = MainRequest.objects.filter(Maintenance_Type='MEP',Zone__in=['6','7','8','9','10'],status='Completed')
        z6 = MainRequest.objects.filter(Maintenance_Type='MEP', Zone='6').count()
        z7 = MainRequest.objects.filter(Maintenance_Type='MEP', Zone='7').count()
        z8 = MainRequest.objects.filter(Maintenance_Type='MEP', Zone='8').count()
        z9 = MainRequest.objects.filter(Maintenance_Type='MEP', Zone='9').count()
        z10 = MainRequest.objects.filter(Maintenance_Type='MEP', Zone='10').count()
        data = [queryset.count(),queryset1.count(),queryset2.count()]
        data2 = [z6,z7,z8,z9,z10]
        t=['MEP']
        labels2 = ["Zone 06", "Zone 07", "Zone 08",'Zone 09','Zone 10']
        return render(request,'reqtracker/dashboard-super.html',{
            'req':req,
            'labels':labels,
            'data':data,
            'data2':data2,
            'labels2':labels2,
            't':t,
            'queryset':queryset,
            'queryset1':queryset1,
            'queryset2':queryset2         
            })

#view estimation report
def view_estimation(request,r):
    form = CompletionForm

reqtracker/templates/reqtracker/completion_form.html
{% extends 'reqtracker/dashboard.html' %}
{% block content %}
{% load static %}

<style>
    h6{
      color:white;
    }
    #id_work_details{
        width:230px;
    }
    tr{
      background-color:white;
      color:black;
      border:1px;
    }
    table, th, td {
    border: 1px solid black;
    border-collapse: collapse;
    }
    th{
      font-weight: 1000;
    }
  </style>
  <div class="row" style="margin-right: 0px; margin-left: 0px;margin-top:60px; padding: 40px 0px 25px 0px">
    <div class="col-md-5">
        <hr>
        <h5>Form</h5>
        <hr>
        <div class="col-lg-7 mx-auto">
          <div class="card mt-2 mx-auto p-4" style="background: #5881a7 !important;">
            <div class="card-body">
              <div class="container">
                <form id="contact-form" role="form" method="post" action="">
                  {% csrf_token %}
                  <div class="row">
                    <table>
                      <div class="col-md-12">
                        <h6>Request Number</h6>
                        <div class="form-group">
                          <label for="id_Request_Number"
                            >{{form.mr}}</label
                          >
                        </div>
                      </div> 
                      <div class="col-md-12">
                      <h6>Technician Name</h6>
                        <div class="form-group">
                          <label for="id_tech_name"
                            >{{form.tech_name}}</label
                          >
                        </div>
                      </div>
                      <div class="col-md-12">
                      <h6>Item</h6>
                        <div class="form-group">
                          <label for="id_item"
                            >{{form.item}}</label
                          >
                        </div>
                      </div>
                      <div class="col-md-12">
                        <h6>Quantity</h6>
                          <div class="form-group">
                            <label for="id_quantity"
                              >{{form.quantity}}</label
                            >
                          </div>
                      </div>
                      <div class="col-md-12">
                        <h6>Unit</h6>
                          <div class="form-group">
                            <label for="id_unit"
                              >{{form.unit}}</label
                            >
                          </div>
                      </div>  
                      <div class="col-md-12">
                      <h6>Work Details</h6>
                        <div class="form-group" id='id_work_det'>
                          <label for="id_work_details" 
                            >{{form.work_details}}</label
                          >
                        </div>
                      </div>
                    </table>
                </div>
                <div class="row">
                  <div class="col-md-12">
                    <button type="submit" class="btn btn-success btn-block">
                      Update
                    </button>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
    
  {% if requ.count > 0 %}
    <div class="col-md-7">
        <hr>
        <h5>
            Completion Report for <strong><span id='rq'></span></strong>
        </h5>
        <hr>
        {% for i in requ %}
        <table class="table table-sm">
            
            <tr>
                <th>Request Number</th>
                <td>{{i.mr}}</td>
            </tr>
            <tr>
                <th>Technician</th>
                <td>{{i.tech_name}}</td>
            </tr>
            <tr>
                <th>Date Created</th>
                <td>{{i.date_created}}</td>
            </tr>
            <tr>
                <th>Item</th>
                <td>{{i.item}}</td>
            </tr>
            <tr>
                <th>Quantity</th>
                <td>{{i.quantity}}</td>
            </tr>
            <tr>
              <th>Unit</th>
              <td>{{i.unit}}</td>
          </tr>
            <tr>
                <th>Work Details</th>
                <td>{{i.work_details}}</td>
            </tr>
            
        </table>
        <hr>
        {% endfor %}
    </div>
  </div>
  {% endif %}

<script>
    // Setting request number for the estimation automatically
    var url = window.location.pathname;
    console.log(url);
    var patt = /RM\d+/;
    var res = patt.exec(url);
    var r = document.getElementById("id_mr").value = res;
    document.getElementById('rq').innerHTML = res;
    console.log(res);
</script>
{% endblock %}

reqtracker/templates/reqtracker/est_form.html
{% extends 'reqtracker/dashboard.html' %} {% load static %} {% block content %}
<style>
  h6{
    color:white;
  }
</style>
<div class="container">
  <div class="text-center mt-5" style="padding-top: 40px">
    <h2>Update Estimation</h2>
  </div>
  <div class="row">
    <div class="col-lg-7 mx-auto">
      <div class="card mt-2 mx-auto p-4" style="background: #5881a7 !important;">
        <div class="card-body">
          <div class="container">
            <form id="contact-form" role="form" method="POST" action="">
              {% csrf_token %}
              <div class="row">
                <table>
                  <div class="col-md-12">
                    <h6>Request Number</h6>
                    <div class="form-group">
                      <label for="id_mr"
                        >{{form.mr}}</label
                      >
                    </div>
                  </div>
                  <div class="col-md-12">
                    <h6>Item</h6>
                    <div class="form-group">
                      <label for="id_item"
                        >{{form.item}}</label
                      >
                    </div>
                  </div>
                  <div class="col-md-12">
                    <h6>Quantity</h6>
                    <div class="form-group">
                      <label for="id_quantity"
                        >{{form.quantity}}</label
                      >
                    </div>
                  </div>
                  <div class="col-md-12">
                    <h6>Unit</h6>
                    <div class="form-group">
                      <label for="id_unit"
                        >{{form.unit}}</label
                      >
                    </div>
                  </div>
                  <div class="col-md-12">
                    <h6>Work Details</h6>
                    <div class="form-group">
                      <label for="id_work_detials"
                        >{{form.work_details}}</label
                      >
                    </div>
                  </div>
                </table>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <button type="submit" class="btn btn-success btn-block">
                    Update </button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

reqtracker/templates/reqtracker/order_form.html
{% extends 'reqtracker/dashboard.html' %} {% load static %} {% block content %}

<style>
  h6{
    color:white;
  }
</style>
<div class="container">
  <div class="text-center mt-5" style="padding-top: 40px">
    <h1  style='color:black'>Maintenance Request Form</h1>
  </div>
  <div class="row">
    <div class="col-lg-7 mx-auto">
      <div class="card mt-2 mx-auto p-4">
        <div class="card-body">
          <div class="container">
            <form id="contact-form" role="form" method="post" action="">
              {% csrf_token %}
              <div class="row">
                <table>
                  <div class="col-md-12">
                    <h6>Request Number</h6>
                    <div class="form-group">
                      <label for="id_Request_Number"
                        >{{form.Request_Number}}</label
                      >
                    </div>
                  </div>
                  <div class="col-md-12">
                    <h6>Maintenance</h6>
                    <div class="form-group">
                      <label for="id_Maintenance">{{form.Maintenance}}</label>
                    </div>
                  </div>
                  <tr>
                    <div class="col-md-12">
                      <h6>Maintenance Type</h6>
                      <div class="form-group">
                        <label for="id_Maintenance_Type"
                          >{{form.Maintenance_Type}}</label
                        >
                      </div>
                    </div>
                  </tr>
                  <tr>
                    <div class="col-md-12" id="id_Civil">
                      <h6>Nature Civil</h6>
                      <div class="form-group">
                        <label for="id_Nature_Civil"
                          >{{form.Nature_Civil}}</label
                        >
                      </div>
                    </div>
                  </tr>
                  <tr>
                    <div class="col-md-12" id="id_MEP">
                      <h6>Nature MEP</h6>
                      <div class="form-group">
                        <label for="id_Nature_MEP">{{form.Nature_MEP}}</label>
                      </div>
                    </div>
                  </tr>
                  <div class="col-md-12">
                    <h6>Type Nature</h6>
                    <div class="form-group">
                      <label for="id_Type_Nature">{{form.Type_Nature}}</label>
                    </div>
                  </div>
                  <div class="col-md-12">
                    <h6>Zone</h6>
                    <div class="form-group">
                      <label for="id_Zone">{{form.Zone}}</label>
                    </div>
                  </div>
                  <div class="col-md-12">
                    <h6>Flat</h6>
                    <div class="form-group">
                      <label for="id_Flat">{{form.Flat}}</label>
                    </div>
                  </div>
                  <div class="col-md-12">
                    <h6>Building</h6>
                    <div class="form-group">
                      <label for="id_Building">{{form.Building}}</label>
                    </div>
                  </div>
                  <div class="col-md-12">
                    <h6>Floor</h6>
                    <div class="form-group">
                      <label for="id_Floor">{{form.Floor}}</label>
                    </div>
                  </div>
                  <div class="col-md-12">
                    <h6>Complaint Details</h6>
                    <div class="form-group">
                      <label for="id_Complaint_Details"
                        >{{form.Complaint_Details}}</label
                      >
                    </div>
                  </div>
                  <!-- <div class="col-md-12">
                    <h6>Image-1</h6>
                    <div class="form-group">
                      <label for="id_image_1"
                        >{{form.image_1}}</label
                      >
                    </div>
                  </div>
                  <div class="col-md-12">
                    <h6>Image-2</h6>
                    <div class="form-group">
                      <label for="id_image_2"
                        >{{form.image_2}}</label
                      >
                    </div>
                  </div> -->
                </table>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <button type="submit" class="btn btn-success btn-block" style='background-color: #1B2431 !important'>
                    Submit
                  </button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script>
    document
      .getElementById("id_Maintenance_Type")
      .addEventListener("change", function () {
        showMe();
      });
    document.getElementById("id_Civil").style.display = "none";
    document.getElementById("id_MEP").style.display = "none";
    function showMe() {
      var e = document.getElementById("id_Maintenance_Type").value;
      //console.log(e);
      if (e == "Civil") {
        //console.log('CIVIL');
        document.getElementById("id_Civil").style.display = "block";
        document.getElementById("id_MEP").style.display = "none";
      } else if (e == "MEP") {
        //console.log('MEP');
        document.getElementById("id_Civil").style.display = "none";
        document.getElementById("id_MEP").style.display = "block";
      }
    }
  </script>
  {% endblock %}
</div>

reqtracker/templates/reqtracker/status_update.html
{% extends 'reqtracker/dashboard.html' %} {% load static %} {% block content %}
<style>
  h6{
    color:white;
  }
</style>
<div class="container">
  <div class="text-center mt-5" style="padding-top: 40px">
    <h1 style='color:black'>Status Update</h1>
  </div>
  <div class="row">
    <div class="col-lg-7 mx-auto">
      <div class="card mt-2 mx-auto p-4" style="background: #5881a7 !important;">
        <div class="card-body">
          <div class="container">
            <form id="contact-form" role="form" method="post" action="">
              {% csrf_token %}
              <div class="row">
                <table>
                  <div class="col-md-12">
                    <h6>Request Number</h6>
                    <div class="form-group">
                      <label for="id_Request_Number"
                        >{{form.Request_Number}}</label
                      >
                    </div>
                  </div> 
                  <div class="col-md-12">
                  <h6>Status</h6>
                    <div class="form-group">
                      <label for="id_status"
                        >{{form.status}}</label
                      >
                    </div>
                  </div>
                </table>
            </div>
            <div class="row">
              <div class="col-md-12">
                <button type="submit" class="btn btn-success btn-block">
                  Update
                </button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}